install.packages("MASS")
install.packages("ISLR")

library(tidymodels)
library(MASS)
library(ISLR)

set.seed(123)
#STEP 1
#specifiy the mode and type of engine used 
lm_spec <- linear_reg()%>%
  set_mode("regression")%>%
  set_engine("lm")

lm_spec

data(Boston)

#predict the medium value
#contains linear model specification to the boston 
#STEP 2
lm_fit<-lm_spec%>% 
  fit(data = Boston, medv~lstat)
#lm_fit is the fitted model

lm_fit%>%
  pluck("fit")%>%summary()

tidy(lm_fit)

#STEP 3 - Use the fitted model from step 2 
# to predict new y in new data 
predict(lm_fit, new_data = Boston)
#gives s list of values-values generated by 
#the new model 

#augement is also similar to predict()
#but select pulls up the predict variable column
#whihc is medv
#examingin new precucted values
final_model<-
  augment(lm_fit, new_data = Boston)

#Complety different predicting set to previous one
model_spec<-linear_reg()%>%
  set_mode("regression")%>%
  set_engine("lm")

model_fit<-model_spec%>%
  fit(data=Boston, medv~age+crim+rm)

model_pred<-
  predict(model_fit, new_data = Boston)
#using predict() only gives the predicted 
#value only. augement() give predicted variable and 
#all other variables in the dataset 

model_augment<-
  augment(model_fit, new_data = Boston)

data(Boston)

#Rgeression with all variables 

model_lm_spec<-linear_reg()%>%
  set_mode("regression")%>%
  set_engine("lm")

model_lm_fit<- model_lm_spec%>%
  fit(data = Boston, medv~.)

model_lm_augement<-
  augment(model_lm_fit, new_data = Boston)
