---
title: "Iris dataset example"
author: "Maria Prokofieva"
date: "18/08/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

- Reference : https://rviews.rstudio.com/2019/06/19/a-gentle-intro-to-tidymodels/

### Example : iris

```{r}
library(tidymodels)
#install.packages('Rcpp')
library(Rcpp)
# install.packages(c("ranger", "randomForest"))
library(ranger)
library(randomForest)
```

#### Data Sampling

'initial_split' 

```{r}
iris_split <- initial_split(iris, prop = 0.6)
iris_split # testing / training / total 
```

```{r}
iris_split %>% 
  training() %>% 
  glimpse()
```

#### Pre-process interface

- recipe
- prep
- step
  - step_corr() : 
  - step_center()
  - step_scale()


```{r}
iris_split %>%
  training() %>%
  print()
```

```{r}
### 
#### - all_outcomes
#### step_center, step_scale
iris_recipe <- training(iris_split) %>% 
  recipe(Species ~.) %>% # 
  step_corr(all_predictors()) %>% 
  step_center(all_predictors(), -all_outcomes()) %>% 
  step_scale(all_predictors(), -all_outcomes()) %>% 
  prep() # 
```
```{r}
iris_recipe
```

#### Execute the pre-processing
- recipe, bake 함수를 사용
```{r}
iris_testing <- iris_recipe %>% 
  bake(testing(iris_split))
iris_testing %>% glimpse()
```

```{r}
iris_training <- juice(iris_recipe)
glimpse(iris_training)
```

### Model Training

```{r}
iris_ranger <- rand_forest(trees = 100, mode = "classification") %>% 
  set_engine("ranger") %>% 
  fit(Species ~ ., data = iris_training)
```
```{r}
iris_rf <- rand_forest(trees = 100, mode = "classification") %>% 
  set_engine("randomForest") %>% 
  fit(Species ~ ., data = iris_training)
```

### Prediction
```{r}
predict(iris_ranger, iris_testing)
```

- testing data에 예측값을 결합
```{r}
iris_ranger %>% 
  predict(iris_testing) %>% 
  bind_cols(iris_testing) %>% 
  glimpse()
```

### Model Validation
```{r}
iris_ranger %>% 
  predict(iris_testing) %>% 
  bind_cols(iris_testing) %>% 
  metrics(truth = Species, estimate=.pred_class)
```

```{r}
iris_rf %>% 
  predict(iris_testing) %>% 
  bind_cols(iris_testing) %>% 
  metrics(truth = Species, estimate = .pred_class)
```

### Per classifier metric
- class
```{r}
iris_ranger %>% 
  predict(iris_testing, type = "prob") %>% 
  glimpse()
```

```{r}
iris_probs <- iris_ranger %>% 
  predict(iris_testing, type = "prob") %>% 
  bind_cols(iris_testing)
glimpse(iris_probs)
```
- gain_curve : 

```{r}
iris_probs %>% 
  gain_curve(Species, .pred_setosa:.pred_virginica) %>% 
  glimpse()
```

```{r}
iris_probs %>% 
  gain_curve(Species, .pred_setosa:.pred_virginica) %>% 
  autoplot()
```

- ROC curve

```{r}
iris_probs %>% 
  roc_curve(Species, .pred_setosa:.pred_virginica) %>% 
  autoplot()
```

-

```{r}
predict(iris_ranger, iris_testing, type = "prob") %>% 
  bind_cols(predict(iris_ranger, iris_testing)) %>% 
  bind_cols(select(iris_testing, Species)) %>% 
  glimpse()
```

- measure report
```{r}
predict(iris_ranger, iris_testing, type = "prob") %>% 
  bind_cols(predict(iris_ranger, iris_testing)) %>% 
  bind_cols(select(iris_testing, Species)) %>% 
  metrics(Species, .pred_setosa:.pred_virginica, estimate = .pred_class)
```


- Reference : https://rviews.rstudio.com/2019/06/19/a-gentle-intro-to-tidymodels/